# Generated by Django 3.2 on 2022-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='periode',
            field=models.TimeField(null=True),
        ),
    ]
