# Generated by Django 3.2 on 2022-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0005_task_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('SelectStatus', 'SelectStatut'), ('InProgress', 'InProgress'), ('Waiting', 'Waiting'), ('Approuved', 'Approuved'), ('InReview', 'InReview'), ('Finish', 'Finish')], default='SelectStatus', max_length=200),
        ),
    ]
