# Generated by Django 3.2 on 2022-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0006_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Select a Status', 'Select a Statut'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Approuved', 'Approuved'), ('In Review', 'In Review'), ('Finish', 'Finish')], default='SelectStatus', max_length=200),
        ),
    ]
