# Generated by Django 3.2 on 2022-11-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0007_auto_20221109_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Approuved', 'Approuved'), ('In Review', 'In Review'), ('Finish', 'Finish')], default='Select a Status', max_length=200),
        ),
    ]
