# Generated by Django 3.2 on 2022-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Select a Status', 'Select a Status'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Approuved', 'Approuved'), ('In Review', 'In Review'), ('Finish', 'Finish')], max_length=200),
        ),
    ]
