# Generated by Django 3.2 on 2022-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0010_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
