# Generated by Django 3.2 on 2022-11-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0011_modelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelName',
        ),
    ]
