# Generated by Django 3.2 on 2022-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0012_delete_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
