# Generated by Django 3.2 on 2022-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apirest', '0013_auto_20221109_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
